
# Site settings
title: Artificial Intelligence and Statistics Conference
email: 
description: > # this means to ignore newlines until "baseurl:"
  This is the website of the AISTATS conference.
baseurl: "/aistats2015" # the subpath of your site, e.g. /blog/
url: "http://www.aistats.org" # the base hostname & protocol for your site
#twitter_username: aistat
github_username:  aistats
style: aistats

author:
  name: AISTATS
comments: false
plugins:
- jekyll-feed
- jekyll-seo-tag
- jekyll-remote-theme
remote_theme: aistats/jekyll-theme
style: aistats

ghub:
  edit: true
  repository: aistats2015
banner: resort.png
      
# Build settings
markdown: kramdown

# change encoding for the generated output files to utf-8
encoding: utf-8

